# Build
FROM node:10.23.1-alpine3.9 AS BUILD_IMAGE
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY /public ./public
COPY /src ./src
RUN npm install
RUN npm run build

# Production
FROM nginx:1.19.6-alpine
COPY --from=BUILD_IMAGE /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]